apiVersion: v2
name: cluster-azure
type: application
version: 5.1.2
description: A helm chart for creating Cluster API clusters with the Azure infrastructure provider (CAPZ).
icon: https://s.giantswarm.io/app-icons/azure/1/light.svg
home: https://github.com/giantswarm/cluster-azure
sources:
  - https://github.com/giantswarm/cluster-azure
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: phoenix
dependencies:
  - name: cluster
    version: "5.1.2"
    repository: https://giantswarm.github.io/cluster-catalog
  - name: cluster-shared
    version: "0.7.1"
    repository: https://giantswarm.github.io/cluster-catalog
