global:
  managementCluster: test-mc
  metadata:
    name: test-wc-minimal
    organization: test
    preventDeletion: false
    servicePriority: lowest
  components:
    auditd:
      enabled: true
  providerSpecific:
    location: "westeurope"
    subscriptionId: 12345678-abcd-1234-abcd-1234567abcde
  release:
    version: v25.0.0

cluster:
  internal:
    ephemeralConfiguration:
      offlineTesting:
        renderWithoutReleaseResource: true
